# Generated by Django 4.2.2 on 2023-07-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0007_create_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='courseinfo.section'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='courseinfo.student'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='courseinfo.period'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='courseinfo.year'),
        ),
    ]
